# Generated by Django 2.2.1 on 2019-08-06 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20190806_1017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='name',
        ),
        migrations.AddField(
            model_name='contact',
            name='address',
            field=models.CharField(default='Kathmandu', max_length=150),
        ),
        migrations.AddField(
            model_name='contact',
            name='full_name',
            field=models.CharField(default='nitesh', max_length=50, verbose_name='Full Name'),
        ),
        migrations.AddField(
            model_name='contact',
            name='message',
            field=models.TextField(default='this is blabla', max_length=200),
        ),
        migrations.AddField(
            model_name='contact',
            name='phone_number',
            field=models.CharField(default='xyz', max_length=150),
        ),
        migrations.AddField(
            model_name='contact',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(max_length=150, verbose_name='Email'),
        ),
    ]
