# Generated by Django 2.2.1 on 2019-08-06 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20190806_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='full_name',
            field=models.CharField(default='suzzan koirala', max_length=50, verbose_name='Full Name'),
        ),
    ]
