# Generated by Django 2.2.1 on 2019-08-11 03:57

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='new bike', max_length=150)),
                ('image', models.ImageField(blank=True, default='', null=True, upload_to='cart/')),
                ('price', models.FloatField(default=0.0)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('status', models.TextField(choices=[('Started', 'Started'), ('Abandoned', 'Abandoned'), ('Finished', 'Finished')], max_length=120, null=True)),
                ('first_name', models.CharField(default='nitesh', max_length=120)),
                ('last_name', models.CharField(default='pantha', max_length=120)),
                ('Email', models.EmailField(default='niteshraz619@gmail.com', max_length=250, verbose_name='Email')),
                ('address', models.CharField(default='Bhaktapur-5 , Ghattaghar', max_length=250)),
                ('city', models.CharField(default='Bhaktapur', max_length=120)),
                ('payment_method', models.CharField(default='Cash On Delivery', max_length=250)),
                ('bike_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='cart.Bike')),
                ('cart', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='cart.Cart')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('price', models.FloatField(default=0.0)),
                ('bike_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='cart.Bike')),
                ('cart_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='cart.Cart')),
            ],
        ),
    ]
