# Generated by Django 2.2.1 on 2019-08-13 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='cart',
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('price', models.FloatField(default=0.0)),
                ('bike_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='cart.CartItem')),
                ('order_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='cart.Order')),
            ],
        ),
    ]
