# Generated by Django 2.2.4 on 2019-08-15 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_auto_20190815_0921'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='Email',
            new_name='email',
        ),
    ]
