# Generated by Django 2.2.4 on 2019-08-15 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0009_auto_20190815_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.TextField(blank=True, choices=[('Started', 'Started'), ('Abandoned', 'Abandoned'), ('Finished', 'Finished')], max_length=120, null=True),
        ),
    ]
